package minioadm

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/lifecycle"
)

type Rule struct {
	ID          string
	Status      string // "Enabled" | "Disabled"
	Prefix      string
	ExpiryDays  int
	Description string // human-friendly summary
}

// ListLifecycle returns the rules currently attached to the bucket.
//
// "No rules at all" is reported via NoSuchLifecycleConfiguration and translated
// to (nil, nil); every other error is surfaced. This matters because callers
// (AddRule / DeleteRule) read this list and rewrite the *whole* policy via
// SetBucketLifecycle — a transient MinIO error mistaken for "empty" would
// silently truncate existing rules on the next save.
func (c *Client) ListLifecycle(ctx context.Context, bucket string) ([]Rule, error) {
	cfg, err := c.S3.GetBucketLifecycle(ctx, bucket)
	if err != nil {
		if isNoSuchLifecycle(err) {
			return nil, nil
		}
		return nil, err
	}
	if cfg == nil {
		return nil, nil
	}
	out := make([]Rule, 0, len(cfg.Rules))
	for _, r := range cfg.Rules {
		out = append(out, Rule{
			ID:          r.ID,
			Status:      r.Status,
			Prefix:      r.RuleFilter.Prefix,
			ExpiryDays:  int(r.Expiration.Days),
			Description: describeRule(r),
		})
	}
	return out, nil
}

// SaveLifecycle replaces the bucket's lifecycle config with the given rules.
// MinIO/S3 lifecycle is whole-config replace, so callers must pass the full
// desired set (handlers do read-modify-write).
func (c *Client) SaveLifecycle(ctx context.Context, bucket string, rules []Rule) error {
	if len(rules) == 0 {
		// Empty config = remove. minio-go exposes RemoveBucketLifecycle.
		return c.S3.SetBucketLifecycle(ctx, bucket, &lifecycle.Configuration{})
	}
	cfg := &lifecycle.Configuration{}
	for _, r := range rules {
		lr := lifecycle.Rule{
			ID:     r.ID,
			Status: r.Status,
		}
		if r.Prefix != "" {
			lr.RuleFilter = lifecycle.Filter{Prefix: r.Prefix}
		}
		if r.ExpiryDays > 0 {
			lr.Expiration = lifecycle.Expiration{Days: lifecycle.ExpirationDays(r.ExpiryDays)}
		}
		cfg.Rules = append(cfg.Rules, lr)
	}
	return c.S3.SetBucketLifecycle(ctx, bucket, cfg)
}

// AddRule appends a rule and saves. ID is generated by MinIO if empty.
func (c *Client) AddRule(ctx context.Context, bucket string, r Rule) error {
	cur, err := c.ListLifecycle(ctx, bucket)
	if err != nil {
		return err
	}
	if r.ID == "" {
		r.ID = newRuleID(cur)
	}
	if r.Status == "" {
		r.Status = "Enabled"
	}
	return c.SaveLifecycle(ctx, bucket, append(cur, r))
}

// UpdateRule finds rule by ID and replaces it.
func (c *Client) UpdateRule(ctx context.Context, bucket string, r Rule) error {
	cur, err := c.ListLifecycle(ctx, bucket)
	if err != nil {
		return err
	}
	for i, existing := range cur {
		if existing.ID == r.ID {
			cur[i] = r
			return c.SaveLifecycle(ctx, bucket, cur)
		}
	}
	return fmt.Errorf("rule %s not found", r.ID)
}

// DeleteRule removes the rule with the given ID. Returns an error if no rule
// matched, so the UI can surface a meaningful message instead of silently
// "succeeding" by writing the same config back.
func (c *Client) DeleteRule(ctx context.Context, bucket, id string) error {
	cur, err := c.ListLifecycle(ctx, bucket)
	if err != nil {
		return err
	}
	out := make([]Rule, 0, len(cur))
	found := false
	for _, r := range cur {
		if r.ID == id {
			found = true
			continue
		}
		out = append(out, r)
	}
	if !found {
		return fmt.Errorf("rule %q not found", id)
	}
	return c.SaveLifecycle(ctx, bucket, out)
}

func describeRule(r lifecycle.Rule) string {
	if r.Expiration.Days > 0 {
		if r.RuleFilter.Prefix != "" {
			return fmt.Sprintf("expire after %d days (prefix %q)", int(r.Expiration.Days), r.RuleFilter.Prefix)
		}
		return fmt.Sprintf("expire after %d days", int(r.Expiration.Days))
	}
	return "(no expiration set)"
}

// newRuleID returns a short, human-readable ID that doesn't collide with any
// existing rule. Format: rule-N starting from 1.
func newRuleID(existing []Rule) string {
	taken := make(map[string]bool, len(existing))
	for _, r := range existing {
		taken[r.ID] = true
	}
	for i := 1; ; i++ {
		id := fmt.Sprintf("rule-%d", i)
		if !taken[id] {
			return id
		}
	}
}

// isNoSuchLifecycle is true when MinIO is signalling "this bucket has no
// lifecycle config at all". Older minio-go versions only surface this as the
// raw string, hence the fallback. Anything else is a real error.
func isNoSuchLifecycle(err error) bool {
	var e minio.ErrorResponse
	if errors.As(err, &e) && e.Code == "NoSuchLifecycleConfiguration" {
		return true
	}
	return strings.Contains(err.Error(), "NoSuchLifecycleConfiguration")
}
